SELECT gu.USER_ID, gu.NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD gb
JOIN USED_GOODS_USER gu 
ON gb.WRITER_ID = gu.USER_ID
WHERE gb.STATUS = 'DONE'
GROUP BY gu.USER_ID, gu.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;